

function xml2json (){
    var parser = require('xml2json');
 
    var xml = "<INSERTA_XML><Encabezado><PLANTA>1004</PLANTA><TRANSPORTE>0000296687</TRANSPORTE><PATENTE>FYLW-43</PATENTE><NRO_CAMION>000000000000000177</NRO_CAMION><FH_SALIDA_PLANTA>2019-06-22</FH_SALIDA_PLANTA><HORA_SALIDA_PLANTA>08:00</HORA_SALIDA_PLANTA><NRO_SELLO_1>1304771</NRO_SELLO_1><NRO_SELLO_2>1304772</NRO_SELLO_2><NRO_SELLO_3>1304773</NRO_SELLO_3><RUT_CHOFER></RUT_CHOFER><DIG_VERI_CHOFER></DIG_VERI_CHOFER><NOM_CHOFER></NOM_CHOFER></Encabezado> <Detalle><TIPO_GUIA>52</TIPO_GUIA><NRO_GUIA>01359700</NRO_GUIA><FORMULA>02AEFL</FORMULA><DESC_FAMILIA>CERDOS ENGORDA FINAL AMBOS LG</DESC_FAMILIA><DESC_COMP_FAMILIA>ENGORDA FINAL</DESC_COMP_FAMILIA><COD_CENTRO_COSTO>C001108026</COD_CENTRO_COSTO><DESC_CENTRO_COSTO>DV MAITENLAHUE</DESC_CENTRO_COSTO><COD_SECTOR>0000001064</COD_SECTOR><DESC_SECTOR>MAITENLAHUE</DESC_SECTOR><KG_NETO_ALIMENTO>25620</KG_NETO_ALIMENTO><FECHA_DESP>20190624</FECHA_DESP></Detalle></INSERTA_XML>";
    //console.log("input -> %s", xml)
     
    // xml to json
    var json = parser.toJson(xml);
    console.log("to json -> %s", json);
     
    // json to xml
    var xml = parser.toXml(json);
    console.log("back to xml -> %s", xml)
}

xml2json ();